[build]
  base = "src"
  publish = "public"
  command = "hugo --gc --minify --baseURL https://frosty-heisenberg-ea476c.netlify.app/"

[context.production.environment]
  HUGO_VERSION = "0.85.0"

[context.deploy-preview]
  command = "hugo --gc --minify --baseURL https://frosty-heisenberg-ea476c.netlify.app/"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.85.0"

  
